/*
 * This config file is generated by python code, if you don't know what it means, don't change it.
 */
public static class SODirConfig
{
    public readonly static string jsonUnityDir = "$jsonUnityDir$";
    public readonly static string persistentDataUnityPath = "$persistentDataUnityPath$";
}